import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    'nav.home': 'Главная',
    'nav.products': 'Товары',
    'nav.contact': 'Контакты',
    'hero.title': 'Лучшие туры и цены на Пхукете — быстро, удобно, надёжно',
    'hero.subtitle': 'Без хлопот, с гарантией качества. Ваше идеальное путешествие начинается здесь',
    'hero.cta': 'Посмотреть туры',
    'hero.rating': 'на основе',
    'hero.reviews': 'отзывов',
    'products.title': 'Популярные туры',
    'products.subtitle': 'Лучшие экскурсии и трансферы на Пхукете',
    'products.filter.all': 'Все',
    'products.filter.transfer': 'Трансфер',
    'products.filter.islands': 'Острова',
    'products.filter.safari': 'Сафари',
    'products.filter.extreme': 'Экстрим',
    'products.filter.clubs': 'Клубы',
    'products.filter.lake': 'Озеро',
    'products.filter.show': 'Шоу',
    'products.perDay': 'от',
    'products.viewDetails': 'Подробнее',
    'products.bookNow': 'Забронировать',
    'products.location': 'Местоположение',
    'products.guests': 'гостей',
    'products.features': 'Особенности',
    'products.startingFrom': 'Начиная от',
    'products.rentalsAvailable': 'доступно',
    'products.rental': 'тур',
    'products.rentals': 'туров',
    'products.noRentalsFound': 'Ничего не найдено по вашему запросу',
    'products.available': 'доступно',
    'benefits.title': 'Почему мы?',
    'benefits.verified': 'Проверенные туры',
    'benefits.verifiedDesc': 'Все экскурсии проверены и сертифицированы',
    'benefits.support': 'Поддержка 24/7',
    'benefits.supportDesc': 'Мы всегда на связи для вашего комфорта',
    'benefits.price': 'Лучшие цены',
    'benefits.priceDesc': 'Гарантированно низкие цены без скрытых платежей',
    'trust.title': 'Нам доверяют',
    'trust.customers': 'Довольных клиентов',
    'trust.tours': 'Проведенных туров',
    'trust.rating': 'Рейтинг',
    'trust.experience': 'Лет опыта',
    'booking.title': 'Завершите бронирование',
    'booking.name': 'Ваше имя',
    'booking.namePlaceholder': 'Введите ваше полное имя',
    'booking.phone': 'Телефон',
    'booking.phonePlaceholder': 'Введите номер телефона',
    'booking.tourDate': 'Дата тура',
    'booking.tourDatePlaceholder': 'Выберите дату тура',
    'booking.adults': 'Количество взрослых',
    'booking.children': 'Количество детей',
    'booking.back': 'Назад',
    'booking.confirm': 'Подтвердить бронирование',
    'booking.fillFields': 'Пожалуйста, заполните все поля',
    'contact.title': 'Свяжитесь с нами',
    'contact.subtitle': 'Есть вопросы? Наша команда готова помочь вам спланировать идеальную аренду.',
    'contact.name': 'Полное имя',
    'contact.namePlaceholder': 'Иван Иванов',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'ivan@example.com',
    'contact.phone': 'Телефон',
    'contact.phonePlaceholder': '+7 (999) 123-45-67',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Расскажите нам о ваших потребностях в аренде...',
    'contact.send': 'Отправить сообщение',
    'contact.sending': 'Отправка...',
    'contact.success': 'Спасибо! Мы получили ваше сообщение и скоро свяжемся с вами.',
    'contact.required': '*',
    'contact.socialMedia': 'Мы в соцсетях',
    'footer.text': 'Премиум аренда для взыскательных путешественников.',
    'category.Трансфер': 'Трансфер',
    'category.Острова': 'Острова',
    'category.Сафари': 'Сафари',
    'category.Рафтинг': 'Рафтинг',
    'category.Экскурсия': 'Экскурсия',
    'category.Экстрим': 'Экстрим',
    'category.Клубы': 'Клубы',
    'category.Парк': 'Парк',
    'category.Озеро': 'Озеро',
    'category.Шоу': 'Шоу',
    'testimonials.title': 'Отзывы наших клиентов',
    'testimonials.subtitle': 'Узнайте, что говорят о нас наши довольные клиенты',
  },
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.contact': 'Contact',
    'hero.title': 'Best Tours & Prices in Phuket — Fast, Easy, Reliable',
    'hero.subtitle': 'Hassle-free with quality guarantee. Your perfect journey starts here',
    'hero.cta': 'View Tours',
    'hero.rating': 'based on',
    'hero.reviews': 'reviews',
    'products.title': 'Popular Tours',
    'products.subtitle': 'Best tours and transfers in Phuket',
    'products.filter.all': 'All',
    'products.filter.transfer': 'Transfer',
    'products.filter.islands': 'Islands',
    'products.filter.safari': 'Safari',
    'products.filter.extreme': 'Extreme',
    'products.filter.clubs': 'Clubs',
    'products.filter.lake': 'Lake',
    'products.filter.show': 'Show',
    'products.perDay': 'per day',
    'products.viewDetails': 'View Details',
    'products.bookNow': 'Book Now',
    'products.location': 'Location',
    'products.guests': 'guests',
    'products.features': 'Features',
    'products.startingFrom': 'Starting from',
    'booking.title': 'Complete Your Booking',
    'booking.name': 'Your Name',
    'booking.namePlaceholder': 'Enter your full name',
    'booking.phone': 'Phone',
    'booking.phonePlaceholder': 'Enter your phone number',
    'booking.tourDate': 'Tour Date',
    'booking.tourDatePlaceholder': 'Select tour date',
    'booking.adults': 'Adults',
    'booking.children': 'Children',
    'booking.back': 'Back',
    'booking.confirm': 'Confirm Booking',
    'booking.fillFields': 'Please fill in all fields',
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have questions? Our team is here to help you plan your perfect rental experience.',
    'contact.name': 'Full Name',
    'contact.namePlaceholder': 'John Doe',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.phone': 'Phone',
    'contact.phonePlaceholder': '+1 (555) 000-0000',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us about your rental needs...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success': 'Thank you! We\'ve received your message and will get back to you soon.',
    'contact.required': '*',
    'contact.socialMedia': 'Follow Us on Social Media',
    'footer.text': 'Premium rentals for discerning travelers.',
    'products.rentalsAvailable': 'available',
    'products.rental': 'tour',
    'products.rentals': 'tours',
    'products.noRentalsFound': 'No tours found matching your criteria',
    'products.available': 'available',
    'benefits.title': 'Why Choose Us?',
    'benefits.verified': 'Verified Tours',
    'benefits.verifiedDesc': 'All tours are verified and certified',
    'benefits.support': '24/7 Support',
    'benefits.supportDesc': 'We are always available for your comfort',
    'benefits.price': 'Best Prices',
    'benefits.priceDesc': 'Guaranteed low prices with no hidden fees',
    'trust.title': 'Trusted by Many',
    'trust.customers': 'Happy Customers',
    'trust.tours': 'Tours Completed',
    'trust.rating': 'Rating',
    'trust.experience': 'Years Experience',
    'category.Трансфер': 'Трансфер',
    'category.Острова': 'Острова',
    'category.Сафари': 'Сафари',
    'category.Рафтинг': 'Рафтинг',
    'category.Экскурсия': 'Экскурсия',
    'category.Экстрим': 'Экстрим',
    'category.Клубы': 'Клубы',
    'category.Парк': 'Парк',
    'category.Озеро': 'Озеро',
    'category.Шоу': 'Шоу',
    'testimonials.title': 'Customer Reviews',
    'testimonials.subtitle': 'See what our happy customers are saying about us',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
