import { createContext, useContext, useState, useEffect, useMemo, useCallback, ReactNode } from 'react';

type Language = 'ru' | 'en' | 'kk' | 'ky' | 'az' | 'zh' | 'fr' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const languageConfig = {
  ru: { code: 'ru', flag: '🇷🇺', label: 'RU' },
  en: { code: 'en', flag: '🇬🇧', label: 'EN' },
  kk: { code: 'kk', flag: '🇰🇿', label: 'KZ' },
  ky: { code: 'ky', flag: '🇰🇬', label: 'KG' },
  az: { code: 'az', flag: '🇦🇿', label: 'AZ' },
  zh: { code: 'zh', flag: '🇨🇳', label: 'ZH' },
  fr: { code: 'fr', flag: '🇫🇷', label: 'FR' },
  uz: { code: 'uz', flag: '🇺🇿', label: 'UZ' },
};

const translations = {
  ru: {
    'nav.home': 'Главная',
    'nav.products': 'Товары',
    'nav.contact': 'Контакты',
    'hero.title': 'Лучшие туры и цены на Пхукете - быстро, удобно, надёжно',
    'hero.subtitle': 'Гарантия низкой цены. Только проверенные туры и партнеры',
    'hero.cta': 'Посмотреть туры',
    'hero.rating': 'на основе',
    'hero.reviews': 'отзывов',
    'products.title': 'Популярные туры',
    'products.subtitle': 'Лучшие экскурсии и трансферы на Пхукете',
    'products.searchPlaceholder': 'Поиск туров...',
    'products.filter.all': 'Все',
    'products.filter.transfer': 'Трансфер',
    'products.filter.islands': 'Острова',
    'products.filter.mainland': 'Тур на материке',
    'products.filter.extreme': 'Экстрим',
    'products.filter.clubs': 'Клубы',
    'products.filter.show': 'Шоу',
    'products.filter.insta': 'Инста туры',
    'products.filter.private': 'Приват туры',
    'products.perDay': 'от',
    'products.viewDetails': 'Подробнее',
    'products.bookNow': 'Забронировать',
    'products.location': 'Местоположение',
    'products.guests': 'гостей',
    'products.features': 'Особенности',
    'products.startingFrom': 'Начиная от',
    'products.rentalsAvailable': 'доступно',
    'products.rental': 'тур',
    'products.rentals': 'туров',
    'products.noRentalsFound': 'Ничего не найдено по вашему запросу',
    'products.available': 'доступно',
    'benefits.title': 'Почему мы?',
    'benefits.verified': 'Проверенные туры',
    'benefits.verifiedDesc': 'Все экскурсии проверены и сертифицированы',
    'benefits.support': 'Поддержка 24/7',
    'benefits.supportDesc': 'Мы всегда на связи для вашего комфорта',
    'benefits.price': 'Лучшие цены',
    'benefits.priceDesc': 'Гарантированно низкие цены без скрытых платежей',
    'trust.title': 'Нам доверяют',
    'trust.customers': 'Довольных клиентов',
    'trust.tours': 'Проведенных туров',
    'trust.rating': 'Рейтинг',
    'trust.experience': 'Лет опыта',
    'booking.title': 'Завершите бронирование',
    'booking.name': 'Ваше имя',
    'booking.namePlaceholder': 'Введите ваше полное имя',
    'booking.phone': 'Телефон (Необязательно)',
    'booking.phonePlaceholder': 'Введите номер телефона',
    'booking.phoneSearchCountry': 'Поиск страны...',
    'booking.phoneNoCountries': 'Страны не найдены',
    'booking.phoneOther': 'Другое',
    'booking.phoneEnterCode': 'Введите код страны',
    'booking.phoneOtherHelper': 'Выберите "Другое" из списка и введите код страны',
    'booking.tourDate': 'Дата тура',
    'booking.tourDatePlaceholder': 'Выберите дату тура',
    'booking.adults': 'Кол-во взрослых',
    'booking.children': 'Кол-во детей',
    'booking.back': 'Назад',
    'booking.confirm': 'Подтвердить бронирование',
    'booking.fillFields': 'Пожалуйста, заполните все поля',
    'booking.privacyConsent': 'Я согласен с',
    'booking.privacyPolicy': 'Политикой конфиденциальности',
    'booking.and': 'и',
    'booking.termsOfService': 'Условиями использования',
    'contact.title': 'Свяжитесь с нами',
    'contact.subtitle': 'Есть вопросы? Наша команда готова помочь вам спланировать идеальную аренду.',
    'contact.name': 'Полное имя',
    'contact.namePlaceholder': 'Иван Иванов',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'ivan@example.com',
    'contact.phone': 'Телефон (Необязательно)',
    'contact.phonePlaceholder': '+7 (999) 123-45-67',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Расскажите нам о ваших потребностях в аренде...',
    'contact.send': 'Отправить сообщение',
    'contact.sending': 'Отправка...',
    'contact.success': 'Спасибо! Мы получили ваше сообщение и скоро свяжемся с вами.',
    'contact.required': '*',
    'contact.socialMedia': 'Мы в соцсетях',
    'footer.text': 'Премиум аренда для взыскательных путешественников.',
    'category.Трансфер': 'Трансфер',
    'category.Острова': 'Острова',
    'category.Рафтинг': 'Рафтинг',
    'category.Экскурсия': 'Экскурсия',
    'category.Экстрим': 'Экстрим',
    'category.Клубы': 'Клубы',
    'category.Парк': 'Парк',
    'category.Озеро': 'Тур на материке',
    'category.Шоу': 'Шоу',
    'category.Инста туры': 'Инста туры',
    'category.Приват туры': 'Приват туры',
    'testimonials.title': 'Отзывы наших клиентов',
    'testimonials.subtitle': 'Узнайте, что говорят о нас наши довольные клиенты',
  },
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.contact': 'Contact',
    'hero.title': 'Best Tours & Prices in Phuket - Fast, Easy, Reliable',
    'hero.subtitle': 'Low price guarantee. Only verified tours and partners',
    'hero.cta': 'View Tours',
    'hero.rating': 'based on',
    'hero.reviews': 'reviews',
    'products.title': 'Popular Tours',
    'products.subtitle': 'Best tours and transfers in Phuket',
    'products.searchPlaceholder': 'Search tours...',
    'products.filter.all': 'All',
    'products.filter.transfer': 'Transfer',
    'products.filter.islands': 'Islands',
    'products.filter.mainland': 'Mainland Tour',
    'products.filter.extreme': 'Extreme',
    'products.filter.clubs': 'Clubs',
    'products.filter.show': 'Show',
    'products.filter.insta': 'Insta Tours',
    'products.filter.private': 'Private Tours',
    'products.perDay': 'per day',
    'products.viewDetails': 'View Details',
    'products.bookNow': 'Book Now',
    'products.location': 'Location',
    'products.guests': 'guests',
    'products.features': 'Features',
    'products.startingFrom': 'Starting from',
    'booking.title': 'Complete Your Booking',
    'booking.name': 'Your Name',
    'booking.namePlaceholder': 'Enter your full name',
    'booking.phone': 'Phone (Optional)',
    'booking.phonePlaceholder': 'Enter your phone number',
    'booking.phoneSearchCountry': 'Search country...',
    'booking.phoneNoCountries': 'No countries found',
    'booking.phoneOther': 'Other',
    'booking.phoneEnterCode': 'Enter country code',
    'booking.phoneOtherHelper': 'Select "Other" from dropdown and enter your country code',
    'booking.tourDate': 'Tour Date',
    'booking.tourDatePlaceholder': 'Select tour date',
    'booking.adults': 'Adults',
    'booking.children': 'Children',
    'booking.back': 'Back',
    'booking.confirm': 'Confirm Booking',
    'booking.fillFields': 'Please fill in all fields',
    'booking.privacyConsent': 'I agree to the',
    'booking.privacyPolicy': 'Privacy Policy',
    'booking.and': 'and',
    'booking.termsOfService': 'Terms of Service',
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have questions? Our team is here to help you plan your perfect rental experience.',
    'contact.name': 'Full Name',
    'contact.namePlaceholder': 'John Doe',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.phone': 'Phone (Optional)',
    'contact.phonePlaceholder': '+1 (555) 000-0000',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us about your rental needs...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success': 'Thank you! We\'ve received your message and will get back to you soon.',
    'contact.required': '*',
    'contact.socialMedia': 'Follow Us on Social Media',
    'footer.text': 'Premium rentals for discerning travelers.',
    'products.rentalsAvailable': 'available',
    'products.rental': 'tour',
    'products.rentals': 'tours',
    'products.noRentalsFound': 'No tours found matching your criteria',
    'products.available': 'available',
    'benefits.title': 'Why Choose Us?',
    'benefits.verified': 'Verified Tours',
    'benefits.verifiedDesc': 'All tours are verified and certified',
    'benefits.support': '24/7 Support',
    'benefits.supportDesc': 'We are always available for your comfort',
    'benefits.price': 'Best Prices',
    'benefits.priceDesc': 'Guaranteed low prices with no hidden fees',
    'trust.title': 'Trusted by Many',
    'trust.customers': 'Happy Customers',
    'trust.tours': 'Tours Completed',
    'trust.rating': 'Rating',
    'trust.experience': 'Years Experience',
    'category.Трансфер': 'Transfer',
    'category.Острова': 'Islands',
    'category.Рафтинг': 'Rafting',
    'category.Экскурсия': 'Excursion',
    'category.Экстрим': 'Extreme',
    'category.Клубы': 'Clubs',
    'category.Парк': 'Park',
    'category.Озеро': 'Mainland Tour',
    'category.Шоу': 'Show',
    'category.Инста туры': 'Insta Tours',
    'category.Приват туры': 'Private Tours',
    'testimonials.title': 'Customer Reviews',
    'testimonials.subtitle': 'See what our happy customers are saying about us',
  },
  kk: {
    'nav.home': 'Басты бет',
    'nav.products': 'Өнімдер',
    'nav.contact': 'Байланыс',
    'hero.title': 'Пхукеттегі ең жақсы турлар мен бағалар - жылдам, ыңғайлы, сенімді',
    'hero.subtitle': 'Төмен баға кепілдігі. Тек тексерілген турлар және серіктестер',
    'hero.cta': 'Турларды қарау',
    'hero.rating': 'негізінде',
    'hero.reviews': 'пікірлер',
    'products.title': 'Танымал турлар',
    'products.subtitle': 'Пхукеттегі ең жақсы экскурсиялар мен трансферлер',
    'products.searchPlaceholder': 'Турларды іздеу...',
    'products.filter.all': 'Барлығы',
    'products.filter.transfer': 'Трансфер',
    'products.filter.islands': 'Аралдар',
    'products.filter.mainland': 'Құрлықтағы тур',
    'products.filter.extreme': 'Экстрим',
    'products.filter.clubs': 'Клубтар',
    'products.filter.show': 'Шоу',
    'products.filter.insta': 'Инста турлар',
    'products.filter.private': 'Жеке турлар',
    'products.perDay': 'бастап',
    'products.viewDetails': 'Толығырақ',
    'products.bookNow': 'Брондау',
    'products.location': 'Орналасқан жері',
    'products.guests': 'қонақтар',
    'products.features': 'Ерекшеліктері',
    'products.startingFrom': 'Бастап',
    'products.rentalsAvailable': 'қолжетімді',
    'products.rental': 'тур',
    'products.rentals': 'турлар',
    'products.noRentalsFound': 'Сіздің сұранысыңыз бойынша ештеңе табылмады',
    'products.available': 'қолжетімді',
    'benefits.title': 'Неге біз?',
    'benefits.verified': 'Тексерілген турлар',
    'benefits.verifiedDesc': 'Барлық экскурсиялар тексерілген және сертификатталған',
    'benefits.support': '24/7 қолдау',
    'benefits.supportDesc': 'Біз сіздің жайлылығыңыз үшін әрқашан байланыстамыз',
    'benefits.price': 'Ең жақсы бағалар',
    'benefits.priceDesc': 'Жасырын төлемдерсіз кепілденділірген төмен бағалар',
    'trust.title': 'Бізге сенеді',
    'trust.customers': 'Қанағаттанған клиенттер',
    'trust.tours': 'Өткізілген турлар',
    'trust.rating': 'Рейтинг',
    'trust.experience': 'Жылдық тәжірибе',
    'booking.title': 'Брондауды аяқтаңыз',
    'booking.name': 'Сіздің атыңыз',
    'booking.namePlaceholder': 'Толық атыңызды енгізіңіз',
    'booking.phone': 'Телефон (Міндетті емес)',
    'booking.phonePlaceholder': 'Телефон нөміріңізді енгізіңіз',
    'booking.phoneSearchCountry': 'Елді іздеу...',
    'booking.phoneNoCountries': 'Елдер табылмады',
    'booking.phoneOther': 'Басқа',
    'booking.phoneEnterCode': 'Ел кодын енгізіңіз',
    'booking.phoneOtherHelper': 'Тізімден "Басқа" таңдаңыз және ел кодын енгізіңіз',
    'booking.tourDate': 'Тур күні',
    'booking.tourDatePlaceholder': 'Тур күнін таңдаңыз',
    'booking.adults': 'Ересектер саны',
    'booking.children': 'Балалар саны',
    'booking.back': 'Артқа',
    'booking.confirm': 'Брондауды растау',
    'booking.fillFields': 'Барлық өрістерді толтырыңыз',
    'booking.privacyConsent': 'Мен келісемін',
    'booking.privacyPolicy': 'Құпиялылық саясатымен',
    'booking.and': 'және',
    'booking.termsOfService': 'Қызмет көрсету шарттарымен',
    'contact.title': 'Бізбен байланысыңыз',
    'contact.subtitle': 'Сұрақтарыңыз бар ма? Біздің команда сізге тамаша жалға жоспарлауға көмектесуге дайын.',
    'contact.name': 'Толық аты',
    'contact.namePlaceholder': 'Иван Иванов',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'ivan@example.com',
    'contact.phone': 'Телефон (Міндетті емес)',
    'contact.phonePlaceholder': '+7 (999) 123-45-67',
    'contact.message': 'Хабарлама',
    'contact.messagePlaceholder': 'Жалға алу қажеттіліктеріңіз туралы айтыңыз...',
    'contact.send': 'Хабарлама жіберу',
    'contact.sending': 'Жіберілуде...',
    'contact.success': 'Рақмет! Біз сіздің хабарламаңызды алдық және жақын арада байланысамыз.',
    'contact.required': '*',
    'contact.socialMedia': 'Әлеуметтік желілерде біз',
    'footer.text': 'Талғампаз саяхатшылар үшін премиум жалға алу.',
    'category.Трансфер': 'Трансфер',
    'category.Острова': 'Аралдар',
    'category.Рафтинг': 'Рафтинг',
    'category.Экскурсия': 'Экскурсия',
    'category.Экстрим': 'Экстрим',
    'category.Клубы': 'Клубтар',
    'category.Парк': 'Парк',
    'category.Озеро': 'Құрлықтағы тур',
    'category.Шоу': 'Шоу',
    'category.Инста туры': 'Инста турлар',
    'category.Приват туры': 'Жеке турлар',
    'testimonials.title': 'Біздің клиенттердің пікірлері',
    'testimonials.subtitle': 'Біздің қанағаттанған клиенттеріміз не айтатынын біліңіз',
  },
  ky: {
    'nav.home': 'Башкы бет',
    'nav.products': 'Товарлар',
    'nav.contact': 'Байланыш',
    'hero.title': 'Пхукеттеги эң мыкты турлар жана баалар - тез, ыңгайлуу, ишенимдүү',
    'hero.subtitle': 'Төмөнкү баанын кепилдиги. Текшерилген турлар жана өнөктөштөр гана',
    'hero.cta': 'Турларды көрүү',
    'hero.rating': 'негизинде',
    'hero.reviews': 'пикирлер',
    'products.title': 'Популярдуу турлар',
    'products.subtitle': 'Пхукеттеги эң мыкты экскурсиялар жана трансферлер',
    'products.searchPlaceholder': 'Турларды издөө...',
    'products.filter.all': 'Баары',
    'products.filter.transfer': 'Трансфер',
    'products.filter.islands': 'Аралдар',
    'products.filter.mainland': 'Материктеги тур',
    'products.filter.extreme': 'Экстрим',
    'products.filter.clubs': 'Клубдар',
    'products.filter.show': 'Шоу',
    'products.filter.insta': 'Инста турлар',
    'products.filter.private': 'Жеке турлар',
    'products.perDay': 'башынан',
    'products.viewDetails': 'Кененирээк',
    'products.bookNow': 'Брондоо',
    'products.location': 'Жайгашкан жери',
    'products.guests': 'конокторду',
    'products.features': 'Өзгөчөлүктөрү',
    'products.startingFrom': 'Башынан',
    'products.rentalsAvailable': 'жеткиликтүү',
    'products.rental': 'тур',
    'products.rentals': 'турлар',
    'products.noRentalsFound': 'Сиздин суроо-талабыңызга эч нерсе табылган жок',
    'products.available': 'жеткиликтүү',
    'benefits.title': 'Эмне үчүн биз?',
    'benefits.verified': 'Текшерилген турлар',
    'benefits.verifiedDesc': 'Бардык экскурсиялар текшерилген жана сертификатталган',
    'benefits.support': '24/7 колдоо',
    'benefits.supportDesc': 'Биз сиздин жайлылыгыңыз үчүн ар дайым байланыштабыз',
    'benefits.price': 'Эң мыкты баалар',
    'benefits.priceDesc': 'Жашыруун төлөмдөрсүз кепилденген төмөнкү баалар',
    'trust.title': 'Бизге ишенишет',
    'trust.customers': 'Канааттандырылган кардарлар',
    'trust.tours': 'Өткөрүлгөн турлар',
    'trust.rating': 'Рейтинг',
    'trust.experience': 'Жылдык тажрыйба',
    'booking.title': 'Брондоону аяктаңыз',
    'booking.name': 'Сиздин атыңыз',
    'booking.namePlaceholder': 'Толук атыңызды киргизиңиз',
    'booking.phone': 'Телефон (Милдеттүү эмес)',
    'booking.phonePlaceholder': 'Телефон номуруңузду киргизиңиз',
    'booking.phoneSearchCountry': 'Өлкөнү издөө...',
    'booking.phoneNoCountries': 'Өлкөлөр табылган жок',
    'booking.phoneOther': 'Башка',
    'booking.phoneEnterCode': 'Өлкө кодун киргизиңиз',
    'booking.phoneOtherHelper': 'Тизмеден "Башка" тандаңыз жана өлкө кодун киргизиңиз',
    'booking.tourDate': 'Тур күнү',
    'booking.tourDatePlaceholder': 'Тур күнүн тандаңыз',
    'booking.adults': 'Чоңдордун саны',
    'booking.children': 'Балдардын саны',
    'booking.back': 'Артка',
    'booking.confirm': 'Брондоону ырастоо',
    'booking.fillFields': 'Бардык талааларды толтуруңуз',
    'booking.privacyConsent': 'Мен макулмун',
    'booking.privacyPolicy': 'Купуялуулук саясаты',
    'booking.and': 'жана',
    'booking.termsOfService': 'Кызмат көрсөтүү шарттары',
    'contact.title': 'Биз менен байланышыңыз',
    'contact.subtitle': 'Суроолоруңуз барбы? Биздин команда сизге мыкты ижарага пландаштырууга жардам берүүгө даяр.',
    'contact.name': 'Толук аты',
    'contact.namePlaceholder': 'Иван Иванов',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'ivan@example.com',
    'contact.phone': 'Телефон (Милдеттүү эмес)',
    'contact.phonePlaceholder': '+7 (999) 123-45-67',
    'contact.message': 'Билдирүү',
    'contact.messagePlaceholder': 'Ижара керектөөлөрүңүз жөнүндө айтыңыз...',
    'contact.send': 'Билдирүү жөнөтүү',
    'contact.sending': 'Жөнөтүлүүдө...',
    'contact.success': 'Рахмат! Биз сиздин билдирүүңүздү алдык жана жакында байланышабыз.',
    'contact.required': '*',
    'contact.socialMedia': 'Социалдык тармактарда биз',
    'footer.text': 'Талгамдуу саякатчылар үчүн премиум ижарага алуу.',
    'category.Трансфер': 'Трансфер',
    'category.Острова': 'Аралдар',
    'category.Рафтинг': 'Рафтинг',
    'category.Экскурсия': 'Экскурсия',
    'category.Экстрим': 'Экстрим',
    'category.Клубы': 'Клубдар',
    'category.Парк': 'Парк',
    'category.Озеро': 'Материктеги тур',
    'category.Шоу': 'Шоу',
    'category.Инста туры': 'Инста турлар',
    'category.Приват туры': 'Жеке турлар',
    'testimonials.title': 'Биздин кардарлардын пикирлери',
    'testimonials.subtitle': 'Биздин канааттандырылган кардарларыбыз эмне айтаарын билиңиз',
  },
  az: {
    'nav.home': 'Ana səhifə',
    'nav.products': 'Məhsullar',
    'nav.contact': 'Əlaqə',
    'hero.title': 'Phukettə ən yaxşı turlar və qiymətlər - sürətli, rahat, etibarlı',
    'hero.subtitle': 'Aşağı qiymət zəmanəti. Yalnız yoxlanılmış turlar və tərəfdaşlar',
    'hero.cta': 'Turları göstər',
    'hero.rating': 'əsasında',
    'hero.reviews': 'rəylər',
    'products.title': 'Populyar turlar',
    'products.subtitle': 'Phukettə ən yaxşı ekskursiyalar və transferlər',
    'products.searchPlaceholder': 'Turları axtar...',
    'products.filter.all': 'Hamısı',
    'products.filter.transfer': 'Transfer',
    'products.filter.islands': 'Adalar',
    'products.filter.mainland': 'Materik turu',
    'products.filter.extreme': 'Ekstremal',
    'products.filter.clubs': 'Klublar',
    'products.filter.show': 'Şou',
    'products.filter.insta': 'İnsta turları',
    'products.filter.private': 'Xüsusi turlar',
    'products.perDay': 'başlayaraq',
    'products.viewDetails': 'Ətraflı',
    'products.bookNow': 'İndi sifariş et',
    'products.location': 'Yer',
    'products.guests': 'qonaqlar',
    'products.features': 'Xüsusiyyətlər',
    'products.startingFrom': 'Başlayaraq',
    'products.rentalsAvailable': 'mövcuddur',
    'products.rental': 'tur',
    'products.rentals': 'turlar',
    'products.noRentalsFound': 'Sorğunuza uyğun heç nə tapılmadı',
    'products.available': 'mövcuddur',
    'benefits.title': 'Niyə biz?',
    'benefits.verified': 'Yoxlanılmış turlar',
    'benefits.verifiedDesc': 'Bütün ekskursiyalar yoxlanılmış və sertifikatlaşdırılmışdır',
    'benefits.support': '24/7 dəstək',
    'benefits.supportDesc': 'Biz sizin rahatlığınız üçün həmişə əlaqədəyik',
    'benefits.price': 'Ən yaxşı qiymətlər',
    'benefits.priceDesc': 'Gizli ödənişlər olmadan zəmanətli aşağı qiymətlər',
    'trust.title': 'Bizə etibar edirlər',
    'trust.customers': 'Məmnun müştərilər',
    'trust.tours': 'Keçirilmiş turlar',
    'trust.rating': 'Reytinq',
    'trust.experience': 'İllik təcrübə',
    'booking.title': 'Sifarişi tamamlayın',
    'booking.name': 'Adınız',
    'booking.namePlaceholder': 'Tam adınızı daxil edin',
    'booking.phone': 'Telefon (İxtiyari)',
    'booking.phonePlaceholder': 'Telefon nömrənizi daxil edin',
    'booking.phoneSearchCountry': 'Ölkə axtar...',
    'booking.phoneNoCountries': 'Ölkələr tapilmadi',
    'booking.phoneOther': 'Digər',
    'booking.phoneEnterCode': 'Ölkə kodunu daxil edin',
    'booking.phoneOtherHelper': 'Siyahidan "Digər" seçin və ölkə kodunuzu daxil edin',
    'booking.tourDate': 'Tur tarixi',
    'booking.tourDatePlaceholder': 'Tur tarixini seçin',
    'booking.adults': 'Böyüklərin sayı',
    'booking.children': 'Uşaqların sayı',
    'booking.back': 'Geri',
    'booking.confirm': 'Sifarişi təsdiq et',
    'booking.fillFields': 'Bütün sahələri doldurun',
    'booking.privacyConsent': 'Mən razıyam',
    'booking.privacyPolicy': 'Məxfilik Siyasəti',
    'booking.and': 'və',
    'booking.termsOfService': 'Xidmət Şərtləri',
    'contact.title': 'Bizimlə əlaqə saxlayın',
    'contact.subtitle': 'Suallarınız var? Komandamız sizə mükəmməl icarə planlaşdırmağa kömək etməyə hazırdır.',
    'contact.name': 'Tam ad',
    'contact.namePlaceholder': 'İvan İvanov',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'ivan@example.com',
    'contact.phone': 'Telefon (İxtiyari)',
    'contact.phonePlaceholder': '+7 (999) 123-45-67',
    'contact.message': 'Mesaj',
    'contact.messagePlaceholder': 'İcarə ehtiyaclarınız haqqında bizə danışın...',
    'contact.send': 'Mesaj göndər',
    'contact.sending': 'Göndərilir...',
    'contact.success': 'Təşəkkür edirik! Mesajınızı aldıq və tezliklə sizinlə əlaqə saxlayacağıq.',
    'contact.required': '*',
    'contact.socialMedia': 'Sosial şəbəkələrdə biz',
    'footer.text': 'Tələbkar səyahətçilər üçün premium icarə.',
    'category.Трансфер': 'Transfer',
    'category.Острова': 'Adalar',
    'category.Рафтинг': 'Rafting',
    'category.Экскурсия': 'Ekskursiya',
    'category.Экстрим': 'Ekstremal',
    'category.Клубы': 'Klublar',
    'category.Парк': 'Park',
    'category.Озеро': 'Materik turu',
    'category.Шоу': 'Şou',
    'category.Инста туры': 'İnsta turları',
    'category.Приват туры': 'Xüsusi turlar',
    'testimonials.title': 'Müştərilərimizin rəyləri',
    'testimonials.subtitle': 'Məmnun müştərilərimizin bizim haqqımızda nə dediklərini görün',
  },
  zh: {
    'nav.home': '首页',
    'nav.products': '产品',
    'nav.contact': '联系我们',
    'hero.title': '普吉岛最佳旅游和价格 - 快速、便捷、可靠',
    'hero.subtitle': '低价保证。仅提供经过验证的旅游和合作伙伴',
    'hero.cta': '查看旅游',
    'hero.rating': '基于',
    'hero.reviews': '评论',
    'products.title': '热门旅游',
    'products.subtitle': '普吉岛最佳旅游和接送服务',
    'products.searchPlaceholder': '搜索旅游...',
    'products.filter.all': '全部',
    'products.filter.transfer': '接送',
    'products.filter.islands': '岛屿',
    'products.filter.mainland': '大陆游',
    'products.filter.extreme': '极限运动',
    'products.filter.clubs': '俱乐部',
    'products.filter.show': '表演',
    'products.filter.insta': 'Instagram游',
    'products.filter.private': '私人游',
    'products.perDay': '起',
    'products.viewDetails': '查看详情',
    'products.bookNow': '立即预订',
    'products.location': '位置',
    'products.guests': '位客人',
    'products.features': '特色',
    'products.startingFrom': '起价',
    'products.rentalsAvailable': '可用',
    'products.rental': '旅游',
    'products.rentals': '旅游',
    'products.noRentalsFound': '未找到符合您条件的旅游',
    'products.available': '可用',
    'benefits.title': '为什么选择我们？',
    'benefits.verified': '经过验证的旅游',
    'benefits.verifiedDesc': '所有旅游均经过验证和认证',
    'benefits.support': '24/7 支持',
    'benefits.supportDesc': '我们随时为您提供舒适服务',
    'benefits.price': '最优价格',
    'benefits.priceDesc': '保证低价，无隐藏费用',
    'trust.title': '深受信赖',
    'trust.customers': '满意客户',
    'trust.tours': '完成的旅游',
    'trust.rating': '评分',
    'trust.experience': '年经验',
    'booking.title': '完成您的预订',
    'booking.name': '您的姓名',
    'booking.namePlaceholder': '请输入您的全名',
    'booking.phone': '电话（可选）',
    'booking.phonePlaceholder': '请输入您的电话号码',
    'booking.phoneSearchCountry': '搜索国家...',
    'booking.phoneNoCountries': '未找到国家',
    'booking.phoneOther': '其他',
    'booking.phoneEnterCode': '输入国家代码',
    'booking.phoneOtherHelper': '从下拉列表中选择“其他”并输入您的国家代码',
    'booking.tourDate': '旅游日期',
    'booking.tourDatePlaceholder': '选择旅游日期',
    'booking.adults': '成人人数',
    'booking.children': '儿童人数',
    'booking.back': '返回',
    'booking.confirm': '确认预订',
    'booking.fillFields': '请填写所有字段',
    'booking.privacyConsent': '我同意',
    'booking.privacyPolicy': '隐私政策',
    'booking.and': '和',
    'booking.termsOfService': '服务条款',
    'contact.title': '联系我们',
    'contact.subtitle': '有问题吗？我们的团队随时准备帮助您规划完美的租赁体验。',
    'contact.name': '全名',
    'contact.namePlaceholder': '张三',
    'contact.email': '电子邮件',
    'contact.emailPlaceholder': 'zhang@example.com',
    'contact.phone': '电话（可选）',
    'contact.phonePlaceholder': '+86 138 0000 0000',
    'contact.message': '留言',
    'contact.messagePlaceholder': '告诉我们您的租赁需求...',
    'contact.send': '发送消息',
    'contact.sending': '发送中...',
    'contact.success': '谢谢！我们已收到您的消息，将尽快与您联系。',
    'contact.required': '*',
    'contact.socialMedia': '在社交媒体上关注我们',
    'footer.text': '为挑剔的旅行者提供高端租赁服务。',
    'category.Трансфер': '接送',
    'category.Острова': '岛屿',
    'category.Рафтинг': '漂流',
    'category.Экскурсия': '游览',
    'category.Экстрим': '极限运动',
    'category.Клубы': '俱乐部',
    'category.Парк': '公园',
    'category.Озеро': '大陆游',
    'category.Шоу': '表演',
    'category.Инста туры': 'Instagram游',
    'category.Приват туры': '私人游',
    'testimonials.title': '客户评价',
    'testimonials.subtitle': '看看我们满意的客户怎么说',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.products': 'Produits',
    'nav.contact': 'Contact',
    'hero.title': 'Meilleurs circuits et prix à Phuket - Rapide, facile, fiable',
    'hero.subtitle': 'Garantie du meilleur prix. Uniquement des circuits et partenaires vérifiés',
    'hero.cta': 'Voir les circuits',
    'hero.rating': 'basé sur',
    'hero.reviews': 'avis',
    'products.title': 'Circuits populaires',
    'products.subtitle': 'Meilleurs circuits et transferts à Phuket',
    'products.searchPlaceholder': 'Rechercher des circuits...',
    'products.filter.all': 'Tous',
    'products.filter.transfer': 'Transfert',
    'products.filter.islands': 'Îles',
    'products.filter.mainland': 'Circuit continental',
    'products.filter.extreme': 'Extrême',
    'products.filter.clubs': 'Clubs',
    'products.filter.show': 'Spectacle',
    'products.filter.insta': 'Circuits Insta',
    'products.filter.private': 'Circuits privés',
    'products.perDay': 'à partir de',
    'products.viewDetails': 'Voir les détails',
    'products.bookNow': 'Réserver maintenant',
    'products.location': 'Emplacement',
    'products.guests': 'personnes',
    'products.features': 'Caractéristiques',
    'products.startingFrom': 'À partir de',
    'products.rentalsAvailable': 'disponible',
    'products.rental': 'circuit',
    'products.rentals': 'circuits',
    'products.noRentalsFound': 'Aucun circuit trouvé correspondant à vos critères',
    'products.available': 'disponible',
    'benefits.title': 'Pourquoi nous choisir ?',
    'benefits.verified': 'Circuits vérifiés',
    'benefits.verifiedDesc': 'Tous les circuits sont vérifiés et certifiés',
    'benefits.support': 'Support 24/7',
    'benefits.supportDesc': 'Nous sommes toujours disponibles pour votre confort',
    'benefits.price': 'Meilleurs prix',
    'benefits.priceDesc': 'Prix bas garantis sans frais cachés',
    'trust.title': 'Ils nous font confiance',
    'trust.customers': 'Clients satisfaits',
    'trust.tours': 'Circuits effectués',
    'trust.rating': 'Note',
    'trust.experience': 'Années d\'expérience',
    'booking.title': 'Finalisez votre réservation',
    'booking.name': 'Votre nom',
    'booking.namePlaceholder': 'Entrez votre nom complet',
    'booking.phone': 'Téléphone (Facultatif)',
    'booking.phonePlaceholder': 'Entrez votre numéro de téléphone',
    'booking.phoneSearchCountry': 'Rechercher un pays...',
    'booking.phoneNoCountries': 'Aucun pays trouvé',
    'booking.phoneOther': 'Autre',
    'booking.phoneEnterCode': 'Entrez le code du pays',
    'booking.phoneOtherHelper': 'Sélectionnez "Autre" dans la liste et entrez votre code pays',
    'booking.tourDate': 'Date du circuit',
    'booking.tourDatePlaceholder': 'Sélectionnez la date du circuit',
    'booking.adults': 'Nombre d\'adultes',
    'booking.children': 'Nombre d\'enfants',
    'booking.back': 'Retour',
    'booking.confirm': 'Confirmer la réservation',
    'booking.fillFields': 'Veuillez remplir tous les champs',
    'booking.privacyConsent': 'J\'accepte',
    'booking.privacyPolicy': 'la Politique de confidentialité',
    'booking.and': 'et',
    'booking.termsOfService': 'les Conditions d\'utilisation',
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Des questions ? Notre équipe est là pour vous aider à planifier votre location parfaite.',
    'contact.name': 'Nom complet',
    'contact.namePlaceholder': 'Jean Dupont',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'jean@example.com',
    'contact.phone': 'Téléphone (Facultatif)',
    'contact.phonePlaceholder': '+33 6 00 00 00 00',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Parlez-nous de vos besoins de location...',
    'contact.send': 'Envoyer le message',
    'contact.sending': 'Envoi en cours...',
    'contact.success': 'Merci ! Nous avons reçu votre message et vous répondrons bientôt.',
    'contact.required': '*',
    'contact.socialMedia': 'Suivez-nous sur les réseaux sociaux',
    'footer.text': 'Locations premium pour voyageurs exigeants.',
    'category.Трансфер': 'Transfert',
    'category.Острова': 'Îles',
    'category.Рафтинг': 'Rafting',
    'category.Экскурсия': 'Excursion',
    'category.Экстрим': 'Extrême',
    'category.Клубы': 'Clubs',
    'category.Парк': 'Parc',
    'category.Озеро': 'Circuit continental',
    'category.Шоу': 'Spectacle',
    'category.Инста туры': 'Circuits Insta',
    'category.Приват туры': 'Circuits privés',
    'testimonials.title': 'Avis clients',
    'testimonials.subtitle': 'Découvrez ce que disent nos clients satisfaits',
  },
  uz: {
    'nav.home': 'Bosh sahifa',
    'nav.products': 'Mahsulotlar',
    'nav.contact': 'Aloqa',
    'hero.title': 'Phuketdagi eng yaxshi turlar va narxlar - Tez, qulay, ishonchli',
    'hero.subtitle': 'Past narx kafolati. Faqat tekshirilgan turlar va hamkorlar',
    'hero.cta': 'Turlarni ko\'rish',
    'hero.rating': 'asosida',
    'hero.reviews': 'sharhlar',
    'products.title': 'Mashhur turlar',
    'products.subtitle': 'Phuketdagi eng yaxshi ekskursiyalar va transferlar',
    'products.searchPlaceholder': 'Turlarni qidirish...',
    'products.filter.all': 'Hammasi',
    'products.filter.transfer': 'Transfer',
    'products.filter.islands': 'Orollar',
    'products.filter.mainland': 'Materik turi',
    'products.filter.extreme': 'Ekstremal',
    'products.filter.clubs': 'Klublar',
    'products.filter.show': 'Shou',
    'products.filter.insta': 'Insta turlari',
    'products.filter.private': 'Xususiy turlar',
    'products.perDay': 'dan boshlab',
    'products.viewDetails': 'Batafsil',
    'products.bookNow': 'Buyurtma berish',
    'products.location': 'Joylashuv',
    'products.guests': 'mehmonlar',
    'products.features': 'Xususiyatlar',
    'products.startingFrom': 'Dan boshlab',
    'products.rentalsAvailable': 'mavjud',
    'products.rental': 'tur',
    'products.rentals': 'turlar',
    'products.noRentalsFound': 'Sizning so\'rovingiz bo\'yicha hech narsa topilmadi',
    'products.available': 'mavjud',
    'benefits.title': 'Nega biz?',
    'benefits.verified': 'Tekshirilgan turlar',
    'benefits.verifiedDesc': 'Barcha ekskursiyalar tekshirilgan va sertifikatlangan',
    'benefits.support': '24/7 qo\'llab-quvvatlash',
    'benefits.supportDesc': 'Biz sizning qulayligingiz uchun doimo aloqadamiz',
    'benefits.price': 'Eng yaxshi narxlar',
    'benefits.priceDesc': 'Yashirin to\'lovlarsiz kafolatlangan past narxlar',
    'trust.title': 'Bizga ishonishadi',
    'trust.customers': 'Mamnun mijozlar',
    'trust.tours': 'O\'tkazilgan turlar',
    'trust.rating': 'Reyting',
    'trust.experience': 'Yillik tajriba',
    'booking.title': 'Buyurtmani yakunlang',
    'booking.name': 'Sizning ismingiz',
    'booking.namePlaceholder': 'To\'liq ismingizni kiriting',
    'booking.phone': 'Telefon (Ixtiyoriy)',
    'booking.phonePlaceholder': 'Telefon raqamingizni kiriting',
    'booking.phoneSearchCountry': 'Mamlakatni qidirish...',
    'booking.phoneNoCountries': 'Mamlakatlar topilmadi',
    'booking.phoneOther': 'Boshqa',
    'booking.phoneEnterCode': 'Mamlakat kodini kiriting',
    'booking.phoneOtherHelper': 'Ro\'yxatdan "Boshqa" ni tanlang va mamlakat kodingizni kiriting',
    'booking.tourDate': 'Tur sanasi',
    'booking.tourDatePlaceholder': 'Tur sanasini tanlang',
    'booking.adults': 'Kattalar soni',
    'booking.children': 'Bolalar soni',
    'booking.back': 'Orqaga',
    'booking.confirm': 'Buyurtmani tasdiqlash',
    'booking.fillFields': 'Barcha maydonlarni to\'ldiring',
    'booking.privacyConsent': 'Men roziman',
    'booking.privacyPolicy': 'Maxfiylik siyosati',
    'booking.and': 'va',
    'booking.termsOfService': 'Foydalanish shartlari',
    'contact.title': 'Biz bilan bog\'laning',
    'contact.subtitle': 'Savollaringiz bormi? Bizning jamoamiz sizga mukammal ijaraga rejalashtirish uchun yordam berishga tayyor.',
    'contact.name': 'To\'liq ism',
    'contact.namePlaceholder': 'Ivan Ivanov',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'ivan@example.com',
    'contact.phone': 'Telefon (Ixtiyoriy)',
    'contact.phonePlaceholder': '+998 90 123 45 67',
    'contact.message': 'Xabar',
    'contact.messagePlaceholder': 'Ijara ehtiyojlaringiz haqida bizga xabar bering...',
    'contact.send': 'Xabar yuborish',
    'contact.sending': 'Yuborilmoqda...',
    'contact.success': 'Rahmat! Biz sizning xabaringizni oldik va tez orada siz bilan bog\'lanamiz.',
    'contact.required': '*',
    'contact.socialMedia': 'Ijtimoiy tarmoqlarda biz',
    'footer.text': 'Talabchan sayohatchilar uchun premium ijara.',
    'category.Трансфер': 'Transfer',
    'category.Острова': 'Orollar',
    'category.Рафтинг': 'Rafting',
    'category.Экскурсия': 'Ekskursiya',
    'category.Экстрим': 'Ekstremal',
    'category.Клубы': 'Klublar',
    'category.Парк': 'Park',
    'category.Озеро': 'Materik turi',
    'category.Шоу': 'Shou',
    'category.Инста туры': 'Insta turlari',
    'category.Приват туры': 'Xususiy turlar',
    'testimonials.title': 'Mijozlarimizning sharhlari',
    'testimonials.subtitle': 'Mamnun mijozlarimiz biz haqimizda nima deyishlarini bilib oling',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('lang') as Language;
    return saved && ['ru', 'en', 'kk', 'ky', 'az', 'zh', 'fr', 'uz'].includes(saved) ? saved : 'ru';
  });

  useEffect(() => {
    localStorage.setItem('lang', language);

    if (typeof window !== 'undefined' && typeof window.gtag === 'function') {
      window.gtag('event', 'language_change', {
        language_code: language,
        language_label: languageConfig[language].label
      });
    }
  }, [language]);

  const t = useCallback((key: string): string => {
    const langTranslations = translations[language] as Record<string, string>;
    const ruTranslations = translations['ru'] as Record<string, string>;
    return langTranslations[key] || ruTranslations[key] || key;
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
