import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'ru' | 'en' | 'kk' | 'ky' | 'az';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const languageConfig = {
  ru: { code: 'ru', flag: '🇷🇺', label: 'RU' },
  en: { code: 'en', flag: '🇬🇧', label: 'EN' },
  kk: { code: 'kk', flag: '🇰🇿', label: 'KZ' },
  ky: { code: 'ky', flag: '🇰🇬', label: 'KG' },
  az: { code: 'az', flag: '🇦🇿', label: 'AZ' },
};

const translations = {
  ru: {
    'nav.home': 'Главная',
    'nav.products': 'Товары',
    'nav.contact': 'Контакты',
    'hero.title': 'Лучшие туры и цены на Пхукете — быстро, удобно, надёжно',
    'hero.subtitle': 'Гарантия низкой цены. Только проверенные туры и партнеры',
    'hero.cta': 'Посмотреть туры',
    'hero.rating': 'на основе',
    'hero.reviews': 'отзывов',
    'products.title': 'Популярные туры',
    'products.subtitle': 'Лучшие экскурсии и трансферы на Пхукете',
    'products.filter.all': 'Все',
    'products.filter.transfer': 'Трансфер',
    'products.filter.islands': 'Острова',
    'products.filter.safari': 'Сафари',
    'products.filter.extreme': 'Экстрим',
    'products.filter.clubs': 'Клубы',
    'products.filter.lake': 'Озеро',
    'products.filter.show': 'Шоу',
    'products.perDay': 'от',
    'products.viewDetails': 'Подробнее',
    'products.bookNow': 'Забронировать',
    'products.location': 'Местоположение',
    'products.guests': 'гостей',
    'products.features': 'Особенности',
    'products.startingFrom': 'Начиная от',
    'products.rentalsAvailable': 'доступно',
    'products.rental': 'тур',
    'products.rentals': 'туров',
    'products.noRentalsFound': 'Ничего не найдено по вашему запросу',
    'products.available': 'доступно',
    'benefits.title': 'Почему мы?',
    'benefits.verified': 'Проверенные туры',
    'benefits.verifiedDesc': 'Все экскурсии проверены и сертифицированы',
    'benefits.support': 'Поддержка 24/7',
    'benefits.supportDesc': 'Мы всегда на связи для вашего комфорта',
    'benefits.price': 'Лучшие цены',
    'benefits.priceDesc': 'Гарантированно низкие цены без скрытых платежей',
    'trust.title': 'Нам доверяют',
    'trust.customers': 'Довольных клиентов',
    'trust.tours': 'Проведенных туров',
    'trust.rating': 'Рейтинг',
    'trust.experience': 'Лет опыта',
    'booking.title': 'Завершите бронирование',
    'booking.name': 'Ваше имя',
    'booking.namePlaceholder': 'Введите ваше полное имя',
    'booking.phone': 'Телефон',
    'booking.phonePlaceholder': 'Введите номер телефона',
    'booking.tourDate': 'Дата тура',
    'booking.tourDatePlaceholder': 'Выберите дату тура',
    'booking.adults': 'Количество взрослых',
    'booking.children': 'Количество детей',
    'booking.back': 'Назад',
    'booking.confirm': 'Подтвердить бронирование',
    'booking.fillFields': 'Пожалуйста, заполните все поля',
    'contact.title': 'Свяжитесь с нами',
    'contact.subtitle': 'Есть вопросы? Наша команда готова помочь вам спланировать идеальную аренду.',
    'contact.name': 'Полное имя',
    'contact.namePlaceholder': 'Иван Иванов',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'ivan@example.com',
    'contact.phone': 'Телефон',
    'contact.phonePlaceholder': '+7 (999) 123-45-67',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Расскажите нам о ваших потребностях в аренде...',
    'contact.send': 'Отправить сообщение',
    'contact.sending': 'Отправка...',
    'contact.success': 'Спасибо! Мы получили ваше сообщение и скоро свяжемся с вами.',
    'contact.required': '*',
    'contact.socialMedia': 'Мы в соцсетях',
    'footer.text': 'Премиум аренда для взыскательных путешественников.',
    'category.Трансфер': 'Трансфер',
    'category.Острова': 'Острова',
    'category.Сафари': 'Сафари',
    'category.Рафтинг': 'Рафтинг',
    'category.Экскурсия': 'Экскурсия',
    'category.Экстрим': 'Экстрим',
    'category.Клубы': 'Клубы',
    'category.Парк': 'Парк',
    'category.Озеро': 'Озеро',
    'category.Шоу': 'Шоу',
    'testimonials.title': 'Отзывы наших клиентов',
    'testimonials.subtitle': 'Узнайте, что говорят о нас наши довольные клиенты',
  },
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.contact': 'Contact',
    'hero.title': 'Best Tours & Prices in Phuket — Fast, Easy, Reliable',
    'hero.subtitle': 'Low price guarantee. Only verified tours and partners',
    'hero.cta': 'View Tours',
    'hero.rating': 'based on',
    'hero.reviews': 'reviews',
    'products.title': 'Popular Tours',
    'products.subtitle': 'Best tours and transfers in Phuket',
    'products.filter.all': 'All',
    'products.filter.transfer': 'Transfer',
    'products.filter.islands': 'Islands',
    'products.filter.safari': 'Safari',
    'products.filter.extreme': 'Extreme',
    'products.filter.clubs': 'Clubs',
    'products.filter.lake': 'Lake',
    'products.filter.show': 'Show',
    'products.perDay': 'per day',
    'products.viewDetails': 'View Details',
    'products.bookNow': 'Book Now',
    'products.location': 'Location',
    'products.guests': 'guests',
    'products.features': 'Features',
    'products.startingFrom': 'Starting from',
    'booking.title': 'Complete Your Booking',
    'booking.name': 'Your Name',
    'booking.namePlaceholder': 'Enter your full name',
    'booking.phone': 'Phone',
    'booking.phonePlaceholder': 'Enter your phone number',
    'booking.tourDate': 'Tour Date',
    'booking.tourDatePlaceholder': 'Select tour date',
    'booking.adults': 'Adults',
    'booking.children': 'Children',
    'booking.back': 'Back',
    'booking.confirm': 'Confirm Booking',
    'booking.fillFields': 'Please fill in all fields',
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have questions? Our team is here to help you plan your perfect rental experience.',
    'contact.name': 'Full Name',
    'contact.namePlaceholder': 'John Doe',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.phone': 'Phone',
    'contact.phonePlaceholder': '+1 (555) 000-0000',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us about your rental needs...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success': 'Thank you! We\'ve received your message and will get back to you soon.',
    'contact.required': '*',
    'contact.socialMedia': 'Follow Us on Social Media',
    'footer.text': 'Premium rentals for discerning travelers.',
    'products.rentalsAvailable': 'available',
    'products.rental': 'tour',
    'products.rentals': 'tours',
    'products.noRentalsFound': 'No tours found matching your criteria',
    'products.available': 'available',
    'benefits.title': 'Why Choose Us?',
    'benefits.verified': 'Verified Tours',
    'benefits.verifiedDesc': 'All tours are verified and certified',
    'benefits.support': '24/7 Support',
    'benefits.supportDesc': 'We are always available for your comfort',
    'benefits.price': 'Best Prices',
    'benefits.priceDesc': 'Guaranteed low prices with no hidden fees',
    'trust.title': 'Trusted by Many',
    'trust.customers': 'Happy Customers',
    'trust.tours': 'Tours Completed',
    'trust.rating': 'Rating',
    'trust.experience': 'Years Experience',
    'category.Трансфер': 'Transfer',
    'category.Острова': 'Islands',
    'category.Сафари': 'Safari',
    'category.Рафтинг': 'Rafting',
    'category.Экскурсия': 'Excursion',
    'category.Экстрим': 'Extreme',
    'category.Клубы': 'Clubs',
    'category.Парк': 'Park',
    'category.Озеро': 'Lake',
    'category.Шоу': 'Show',
    'testimonials.title': 'Customer Reviews',
    'testimonials.subtitle': 'See what our happy customers are saying about us',
  },
  kk: {
    'nav.home': 'Басты бет',
    'nav.products': 'Өнімдер',
    'nav.contact': 'Байланыс',
    'hero.title': 'Пхукеттегі ең жақсы турлар мен бағалар — жылдам, ыңғайлы, сенімді',
    'hero.subtitle': 'Төмен баға кепілдігі. Тек тексерілген турлар және серіктестер',
    'hero.cta': 'Турларды қарау',
    'hero.rating': 'негізінде',
    'hero.reviews': 'пікірлер',
    'products.title': 'Танымал турлар',
    'products.subtitle': 'Пхукеттегі ең жақсы экскурсиялар мен трансферлер',
    'products.filter.all': 'Барлығы',
    'products.filter.transfer': 'Трансфер',
    'products.filter.islands': 'Аралдар',
    'products.filter.safari': 'Сафари',
    'products.filter.extreme': 'Экстрим',
    'products.filter.clubs': 'Клубтар',
    'products.filter.lake': 'Көл',
    'products.filter.show': 'Шоу',
    'products.perDay': 'бастап',
    'products.viewDetails': 'Толығырақ',
    'products.bookNow': 'Брондау',
    'products.location': 'Орналасқан жері',
    'products.guests': 'қонақтар',
    'products.features': 'Ерекшеліктері',
    'products.startingFrom': 'Бастап',
    'products.rentalsAvailable': 'қолжетімді',
    'products.rental': 'тур',
    'products.rentals': 'турлар',
    'products.noRentalsFound': 'Сіздің сұранысыңыз бойынша ештеңе табылмады',
    'products.available': 'қолжетімді',
    'benefits.title': 'Неге біз?',
    'benefits.verified': 'Тексерілген турлар',
    'benefits.verifiedDesc': 'Барлық экскурсиялар тексерілген және сертификатталған',
    'benefits.support': '24/7 қолдау',
    'benefits.supportDesc': 'Біз сіздің жайлылығыңыз үшін әрқашан байланыстамыз',
    'benefits.price': 'Ең жақсы бағалар',
    'benefits.priceDesc': 'Жасырын төлемдерсіз кепілденділірген төмен бағалар',
    'trust.title': 'Бізге сенеді',
    'trust.customers': 'Қанағаттанған клиенттер',
    'trust.tours': 'Өткізілген турлар',
    'trust.rating': 'Рейтинг',
    'trust.experience': 'Жылдық тәжірибе',
    'booking.title': 'Брондауды аяқтаңыз',
    'booking.name': 'Сіздің атыңыз',
    'booking.namePlaceholder': 'Толық атыңызды енгізіңіз',
    'booking.phone': 'Телефон',
    'booking.phonePlaceholder': 'Телефон нөміріңізді енгізіңіз',
    'booking.tourDate': 'Тур күні',
    'booking.tourDatePlaceholder': 'Тур күнін таңдаңыз',
    'booking.adults': 'Ересектер саны',
    'booking.children': 'Балалар саны',
    'booking.back': 'Артқа',
    'booking.confirm': 'Брондауды растау',
    'booking.fillFields': 'Барлық өрістерді толтырыңыз',
    'contact.title': 'Бізбен байланысыңыз',
    'contact.subtitle': 'Сұрақтарыңыз бар ма? Біздің команда сізге тамаша жалға жоспарлауға көмектесуге дайын.',
    'contact.name': 'Толық аты',
    'contact.namePlaceholder': 'Иван Иванов',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'ivan@example.com',
    'contact.phone': 'Телефон',
    'contact.phonePlaceholder': '+7 (999) 123-45-67',
    'contact.message': 'Хабарлама',
    'contact.messagePlaceholder': 'Жалға алу қажеттіліктеріңіз туралы айтыңыз...',
    'contact.send': 'Хабарлама жіберу',
    'contact.sending': 'Жіберілуде...',
    'contact.success': 'Рақмет! Біз сіздің хабарламаңызды алдық және жақын арада байланысамыз.',
    'contact.required': '*',
    'contact.socialMedia': 'Әлеуметтік желілерде біз',
    'footer.text': 'Талғампаз саяхатшылар үшін премиум жалға алу.',
    'category.Трансфер': 'Трансфер',
    'category.Острова': 'Аралдар',
    'category.Сафари': 'Сафари',
    'category.Рафтинг': 'Рафтинг',
    'category.Экскурсия': 'Экскурсия',
    'category.Экстрим': 'Экстрим',
    'category.Клубы': 'Клубтар',
    'category.Парк': 'Парк',
    'category.Озеро': 'Көл',
    'category.Шоу': 'Шоу',
    'testimonials.title': 'Біздің клиенттердің пікірлері',
    'testimonials.subtitle': 'Біздің қанағаттанған клиенттеріміз не айтатынын біліңіз',
  },
  ky: {
    'nav.home': 'Башкы бет',
    'nav.products': 'Товарлар',
    'nav.contact': 'Байланыш',
    'hero.title': 'Пхукеттеги эң мыкты турлар жана баалар — тез, ыңгайлуу, ишенимдүү',
    'hero.subtitle': 'Төмөнкү баанын кепилдиги. Текшерилген турлар жана өнөктөштөр гана',
    'hero.cta': 'Турларды көрүү',
    'hero.rating': 'негизинде',
    'hero.reviews': 'пикирлер',
    'products.title': 'Популярдуу турлар',
    'products.subtitle': 'Пхукеттеги эң мыкты экскурсиялар жана трансферлер',
    'products.filter.all': 'Баары',
    'products.filter.transfer': 'Трансфер',
    'products.filter.islands': 'Аралдар',
    'products.filter.safari': 'Сафари',
    'products.filter.extreme': 'Экстрим',
    'products.filter.clubs': 'Клубдар',
    'products.filter.lake': 'Көл',
    'products.filter.show': 'Шоу',
    'products.perDay': 'башынан',
    'products.viewDetails': 'Кененирээк',
    'products.bookNow': 'Брондоо',
    'products.location': 'Жайгашкан жери',
    'products.guests': 'конокторду',
    'products.features': 'Өзгөчөлүктөрү',
    'products.startingFrom': 'Башынан',
    'products.rentalsAvailable': 'жеткиликтүү',
    'products.rental': 'тур',
    'products.rentals': 'турлар',
    'products.noRentalsFound': 'Сиздин суроо-талабыңызга эч нерсе табылган жок',
    'products.available': 'жеткиликтүү',
    'benefits.title': 'Эмне үчүн биз?',
    'benefits.verified': 'Текшерилген турлар',
    'benefits.verifiedDesc': 'Бардык экскурсиялар текшерилген жана сертификатталган',
    'benefits.support': '24/7 колдоо',
    'benefits.supportDesc': 'Биз сиздин жайлылыгыңыз үчүн ар дайым байланыштабыз',
    'benefits.price': 'Эң мыкты баалар',
    'benefits.priceDesc': 'Жашыруун төлөмдөрсүз кепилденген төмөнкү баалар',
    'trust.title': 'Бизге ишенишет',
    'trust.customers': 'Канааттандырылган кардарлар',
    'trust.tours': 'Өткөрүлгөн турлар',
    'trust.rating': 'Рейтинг',
    'trust.experience': 'Жылдык тажрыйба',
    'booking.title': 'Брондоону аяктаңыз',
    'booking.name': 'Сиздин атыңыз',
    'booking.namePlaceholder': 'Толук атыңызды киргизиңиз',
    'booking.phone': 'Телефон',
    'booking.phonePlaceholder': 'Телефон номуруңузду киргизиңиз',
    'booking.tourDate': 'Тур күнү',
    'booking.tourDatePlaceholder': 'Тур күнүн тандаңыз',
    'booking.adults': 'Чоңдордун саны',
    'booking.children': 'Балдардын саны',
    'booking.back': 'Артка',
    'booking.confirm': 'Брондоону ырастоо',
    'booking.fillFields': 'Бардык талааларды толтуруңуз',
    'contact.title': 'Биз менен байланышыңыз',
    'contact.subtitle': 'Суроолоруңуз барбы? Биздин команда сизге мыкты ижарага пландаштырууга жардам берүүгө даяр.',
    'contact.name': 'Толук аты',
    'contact.namePlaceholder': 'Иван Иванов',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'ivan@example.com',
    'contact.phone': 'Телефон',
    'contact.phonePlaceholder': '+7 (999) 123-45-67',
    'contact.message': 'Билдирүү',
    'contact.messagePlaceholder': 'Ижара керектөөлөрүңүз жөнүндө айтыңыз...',
    'contact.send': 'Билдирүү жөнөтүү',
    'contact.sending': 'Жөнөтүлүүдө...',
    'contact.success': 'Рахмат! Биз сиздин билдирүүңүздү алдык жана жакында байланышабыз.',
    'contact.required': '*',
    'contact.socialMedia': 'Социалдык тармактарда биз',
    'footer.text': 'Талгамдуу саякатчылар үчүн премиум ижарага алуу.',
    'category.Трансфер': 'Трансфер',
    'category.Острова': 'Аралдар',
    'category.Сафари': 'Сафари',
    'category.Рафтинг': 'Рафтинг',
    'category.Экскурсия': 'Экскурсия',
    'category.Экстрим': 'Экстрим',
    'category.Клубы': 'Клубдар',
    'category.Парк': 'Парк',
    'category.Озеро': 'Көл',
    'category.Шоу': 'Шоу',
    'testimonials.title': 'Биздин кардарлардын пикирлери',
    'testimonials.subtitle': 'Биздин канааттандырылган кардарларыбыз эмне айтаарын билиңиз',
  },
  az: {
    'nav.home': 'Ana səhifə',
    'nav.products': 'Məhsullar',
    'nav.contact': 'Əlaqə',
    'hero.title': 'Phukettə ən yaxşı turlar və qiymətlər — sürətli, rahat, etibarlı',
    'hero.subtitle': 'Aşağı qiymət zəmanəti. Yalnız yoxlanılmış turlar və tərəfdaşlar',
    'hero.cta': 'Turları göstər',
    'hero.rating': 'əsasında',
    'hero.reviews': 'rəylər',
    'products.title': 'Populyar turlar',
    'products.subtitle': 'Phukettə ən yaxşı ekskursiyalar və transferlər',
    'products.filter.all': 'Hamısı',
    'products.filter.transfer': 'Transfer',
    'products.filter.islands': 'Adalar',
    'products.filter.safari': 'Safari',
    'products.filter.extreme': 'Ekstremal',
    'products.filter.clubs': 'Klublar',
    'products.filter.lake': 'Göl',
    'products.filter.show': 'Şou',
    'products.perDay': 'başlayaraq',
    'products.viewDetails': 'Ətraflı',
    'products.bookNow': 'İndi sifariş et',
    'products.location': 'Yer',
    'products.guests': 'qonaqlar',
    'products.features': 'Xüsusiyyətlər',
    'products.startingFrom': 'Başlayaraq',
    'products.rentalsAvailable': 'mövcuddur',
    'products.rental': 'tur',
    'products.rentals': 'turlar',
    'products.noRentalsFound': 'Sorğunuza uyğun heç nə tapılmadı',
    'products.available': 'mövcuddur',
    'benefits.title': 'Niyə biz?',
    'benefits.verified': 'Yoxlanılmış turlar',
    'benefits.verifiedDesc': 'Bütün ekskursiyalar yoxlanılmış və sertifikatlaşdırılmışdır',
    'benefits.support': '24/7 dəstək',
    'benefits.supportDesc': 'Biz sizin rahatlığınız üçün həmişə əlaqədəyik',
    'benefits.price': 'Ən yaxşı qiymətlər',
    'benefits.priceDesc': 'Gizli ödənişlər olmadan zəmanətli aşağı qiymətlər',
    'trust.title': 'Bizə etibar edirlər',
    'trust.customers': 'Məmnun müştərilər',
    'trust.tours': 'Keçirilmiş turlar',
    'trust.rating': 'Reytinq',
    'trust.experience': 'İllik təcrübə',
    'booking.title': 'Sifarişi tamamlayın',
    'booking.name': 'Adınız',
    'booking.namePlaceholder': 'Tam adınızı daxil edin',
    'booking.phone': 'Telefon',
    'booking.phonePlaceholder': 'Telefon nömrənizi daxil edin',
    'booking.tourDate': 'Tur tarixi',
    'booking.tourDatePlaceholder': 'Tur tarixini seçin',
    'booking.adults': 'Böyüklərin sayı',
    'booking.children': 'Uşaqların sayı',
    'booking.back': 'Geri',
    'booking.confirm': 'Sifarişi təsdiq et',
    'booking.fillFields': 'Bütün sahələri doldurun',
    'contact.title': 'Bizimlə əlaqə saxlayın',
    'contact.subtitle': 'Suallarınız var? Komandamız sizə mükəmməl icarə planlaşdırmağa kömək etməyə hazırdır.',
    'contact.name': 'Tam ad',
    'contact.namePlaceholder': 'İvan İvanov',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'ivan@example.com',
    'contact.phone': 'Telefon',
    'contact.phonePlaceholder': '+7 (999) 123-45-67',
    'contact.message': 'Mesaj',
    'contact.messagePlaceholder': 'İcarə ehtiyaclarınız haqqında bizə danışın...',
    'contact.send': 'Mesaj göndər',
    'contact.sending': 'Göndərilir...',
    'contact.success': 'Təşəkkür edirik! Mesajınızı aldıq və tezliklə sizinlə əlaqə saxlayacağıq.',
    'contact.required': '*',
    'contact.socialMedia': 'Sosial şəbəkələrdə biz',
    'footer.text': 'Tələbkar səyahətçilər üçün premium icarə.',
    'category.Трансфер': 'Transfer',
    'category.Острова': 'Adalar',
    'category.Сафари': 'Safari',
    'category.Рафтинг': 'Rafting',
    'category.Экскурсия': 'Ekskursiya',
    'category.Экстрим': 'Ekstremal',
    'category.Клубы': 'Klublar',
    'category.Парк': 'Park',
    'category.Озеро': 'Göl',
    'category.Шоу': 'Şou',
    'testimonials.title': 'Müştərilərimizin rəyləri',
    'testimonials.subtitle': 'Məmnun müştərilərimizin bizim haqqımızda nə dediklərini görün',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('lang') as Language;
    return saved && ['ru', 'en', 'kk', 'ky', 'az'].includes(saved) ? saved : 'ru';
  });

  useEffect(() => {
    localStorage.setItem('lang', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['ru'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
